// build-app.mjs — production build for the single-file apps.
//
// The app logic lives as inert JSX inside <script id="app-source"> in the
// HTML files (public/index.html, public/index-premium.html). In dev it was
// compiled in the browser by Babel Standalone (~350KB of CDN JS). This script
// does that work once, at build time:
//
//   1. extracts the JSX from each HTML file,
//   2. bundles it (React, ReactDOM, Supabase client, jsQR all local now —
//      zero runtime CDN dependencies except Tailwind, which is also prebuilt),
//   3. prebuilds the Tailwind CSS by scanning the HTML sources,
//   4. verifies every class name the app uses actually exists in the CSS.
//
// After editing the app-source inside an HTML file, re-run:  npm run build:app

import { build } from 'esbuild';
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

const root = process.cwd();

const MODULE_HEADER = `
// Generated by build-app.mjs — production entry.
// Bundles React, ReactDOM, Supabase client and jsQR locally so the app has
// no runtime dependency on CDN scripts (Babel standalone is gone entirely).
import React from 'react';
import ReactDOM from 'react-dom';
import { createClient as ackSupabaseCreateClient } from '@supabase/supabase-js';
import jsQR from 'jsqr';
window.supabase = { createClient: ackSupabaseCreateClient };
`;

function extractAppSource(htmlPath) {
  const html = fs.readFileSync(htmlPath, 'utf8');
  const m = html.match(/<script id="app-source" type="text\/plain">([\s\S]*?)<\/script>/);
  if (!m) throw new Error(`${htmlPath}: no <script id="app-source"> block found`);
  return m[1];
}

async function bundleApp(htmlPath, outfile) {
  const src = extractAppSource(htmlPath);
  await build({
    stdin: {
      contents: MODULE_HEADER + '\n' + src,
      resolveDir: root,
      sourcefile: 'app.jsx',
      loader: 'jsx',
    },
    bundle: true,
    format: 'iife',
    target: ['es2020'],
    minify: true,
    define: { 'process.env.NODE_ENV': '"production"' },
    outfile,
    logLevel: 'warning',
  });
  const size = fs.statSync(outfile).size;
  console.log(`bundled ${path.basename(htmlPath)} -> ${outfile} (${(size / 1024).toFixed(0)} KB)`);
}

async function buildTailwind() {
  const input = 'tailwind-input.css';
  const output = 'public/app.css';
  fs.writeFileSync(input, '@tailwind base;\n@tailwind components;\n@tailwind utilities;\n');
  // --config tailwind.config.cjs keeps CLI detection deterministic.
  execFileSync(
    process.execPath,
    [path.join(root, 'node_modules', 'tailwindcss', 'lib', 'cli.js'), '-i', input, '-o', output, '--minify', '--config', 'tailwind.config.cjs'],
    { stdio: 'inherit' }
  );
  fs.rmSync(input, { force: true });
  console.log(`tailwind -> ${output} (${(fs.statSync(output).size / 1024).toFixed(0)} KB)`);
}

// Escapes a class token the way Tailwind writes it into selectors, so we can
// check whether the generated CSS actually contains the class.
// Commas become hex escapes (\2c ) — Tailwind's cssesc output, not "\,".
function tailwindEscape(token) {
  let out = '';
  for (const c of token) {
    if (c === ',') out += '\\2c ';
    else if (c === ' ') out += '\\_';
    else if (/[\[\]\(\)#\/:.!'%"@*+=?^|~$&<>\\]/.test(c)) out += '\\' + c;
    else out += c;
  }
  return out;
}

// Custom classes defined in the inline <style> blocks (e.g. .ack-blob,
// .ack-grad-text) are not Tailwind utilities — whitelist them.
function customClassesFrom(htmlPath) {
  const html = fs.readFileSync(htmlPath, 'utf8');
  const out = new Set();
  const styleRe = /<style>([\s\S]*?)<\/style>/g;
  let m;
  while ((m = styleRe.exec(html)) !== null) {
    const clsRe = /\.([a-zA-Z_][\w-]*)/g;
    let cm;
    while ((cm = clsRe.exec(m[1])) !== null) out.add(cm[1]);
  }
  return out;
}

function classTokensFrom(htmlPath) {
  const html = fs.readFileSync(htmlPath, 'utf8');
  const tokens = new Set();
  const attrRe = /className\s*=\s*(?:"([^"]*)"|'([^']*)'|`([^`]*)`)/g;
  let m;
  while ((m = attrRe.exec(html)) !== null) {
    const val = m[1] ?? m[2] ?? m[3];
    for (const t of val.split(/\s+/)) {
      // skip template interpolation fragments and empty bits
      if (t && !/\$\{/.test(t) && !/\}/.test(t)) tokens.add(t);
    }
  }
  // inputCls-style constants defined with plain string literals (class-name
  // constants only — a name ending in "Cls" — not data URIs or text blobs)
  const constRe = /const\s+(\w*Cls)\s*=\s*"([^"]+)"/g;
  while ((m = constRe.exec(html)) !== null) {
    for (const t of m[2].split(/\s+/)) if (t) tokens.add(t);
  }
  return tokens;
}

async function verifyCssCoverage() {
  const css = fs.readFileSync('public/app.css', 'utf8');
  const files = ['public/index.html'];
  if (fs.existsSync('public/index-premium.html')) files.push('public/index-premium.html');
  const all = new Set();
  const custom = new Set();
  // Hand-written in the inline <style> blocks (Tailwind can't emit these)
  custom.add('bg-[var(--ack-card)]/75');
  custom.add('bg-[var(--ack-card)]/95');
  for (const f of files) {
    for (const t of classTokensFrom(f)) all.add(t);
    for (const t of customClassesFrom(f)) custom.add(t);
  }
  const missing = [...all].filter((t) => !css.includes('.' + tailwindEscape(t)) && !custom.has(t));
  if (missing.length) {
    console.warn(`CSS coverage: ${all.size} tokens, ${missing.length} MISSING:`);
    for (const t of missing.slice(0, 40)) console.warn('  ' + t);
    process.exitCode = 1;
  } else {
    console.log(`CSS coverage: all ${all.size} class tokens found in app.css (${custom.size} custom inline-style classes whitelisted)`);
  }
}

// ----- main -----
const targets = ['public/index.html', 'public/index-premium.html'];

// Bundle each file separately (their app-source may drift apart over time).
for (const f of targets) {
  if (!fs.existsSync(f)) continue;
  const outfile = f === 'public/index.html' ? 'public/app.bundle.js' : 'public/index-premium.bundle.js';
  await bundleApp(f, outfile);
}

await buildTailwind();
await verifyCssCoverage();
console.log('build:app complete');